import { Command, Flags } from "@oclif/core";

export abstract class BaseCommand extends Command {
  static globalFlags = {
    config: Flags.string({
      char: "c",
      description: "Configuration file path",
    }),
    source: Flags.string({
      char: "s",
      description: "Source language file path (generated by ng extract-i18n)",
    }),
    translations: Flags.string({
      char: "t",
      description: "Paths of translations files, separated by comma (,)",
    }),
  };
}
