name: Deploy
on:
  push:
    branches:
      - beta

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/github
          branches: |
            [
              'main',
              {"name": "beta", "prerelease": true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [semantic_release]
    runs-on: ubuntu-latest
    if: needs.semantic_release.outputs.new_release_published == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build

      - name: Change NPM Version
        uses: fregante/setup-git-user@v1
        env:
          VERSION: ${{ needs.semantic_release.outputs.new_release_version }}
        run: npm version ${VERSION}

      - name: Upload to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "beta"
          check-version: true
